let gtiz_languages = {};
/**
 * English
 * 
 */
gtiz_languages.en = {
  "_description": "English",
  "add" : "Add",
  "add_column" : "Add column",
  "add_metadata" : "Add metadata",
  "add_metadata_for_selection" : "Add metadata for selection",
  "all": "All",
  "all_fields_required_message": "Oops! Fields are all mandatory!",
  "available_zooms": "Available zooms",
  "back_to_full_tree" : "Back to full tree",
  "branch_cutoffs": "Branch cutoffs",
  "branch_style": "Branch style",
  "cannot_remove_column_message" : "I can't remove the indicated column; you'd lose the metadata link with the tree.",
  "cannot_remove_samples_column_message" : "It is not possible to remove sample columns.",
  "category": "Category",
  "category2": "Category 2",
  "centre_tree": "Centre tree",
  "change_language": "Change language",
  "change_language_alert" : "<p><i class=\"iconic iconic-warning-triangle\"></i> By changing language the application will reset.</p>",
  "character": "Character",
  "clean_selection": "Clean selection",
  "closest": "Closest",
  "cluster": "Cluster",
  "clusters": "Clusters",
  "clusters_by_category_and_mst_not_found" : "Clusters by given categories and thresholds were not found: {0}.",
  "clusters_zooms" : "Clusters zooms",
  "clusters_zooms_tools": "Clusters zooms tools",
  "collapse_branches": "Collapse branches",
  "collapse_selected_nodes": "Collapse selected nodes",
  "color_by": "Color by",
  "color_by_defined_category": "Color by defined category",
  "color_scheme": "Color scheme",
  "cookies_notice": "This application does not use cookies.",
  "crn_genome_sequencing": "NRC Genome Sequencing",
  "custom": "Custom",
  "data_category": "Data category",
  "define_a_default_value": "Define a default value",
  "define_a_value_for_selected": "Define a value for selected",
  "define_a_value_for_unselected": "Define a value for not selected",
  "define_column": "Define column",
  "define_for_selected": "Define for selected",
  "define_for_unselected": "Define for not selected",
  "define_metadata": "Define metadata",
  "delete": "Delete",
  "delete_metadata" : "Delete metadata",
  "deselect_all": "Deselect all",
  "display": "Display",
  "do_not_use_current_settings": "Do not use current settings",
  "download": "Download",
  "download_image": "Download image",
  "download_table": "Download table",
  "drop_info": "You can also drag or load a .nwk file followed by a .tsv file containing metadata and optionally a .geojson file containing geo-spatial information. Please read more on our <a href=\"https://github.com/genpat-it/spread/wiki\" target=\"_blank\">wiki</a>.",
  "drop_message": "Please drag here a valid .json file or load it from your file system to start with SPREAD.",
  "dropped_files_alert": "You can only drop one file at a time: a complete <strong>.json</strong> file or alternatively a <strong>.nwk</strong> then a <strong>.tsv</strong> containing metadata, and then optionally a <strong>.geojson</strong> containing spatial informations.",
  "dynamic" : "Dynamic",
  "edit": "Edit",
  "edit_metadata": "Edit metadata",
  "edit_metadata_for_selection": "Edit metadata for selection",
  "expand_all": "Expand all",
  "expand_selected_nodes": "Expand selected nodes",
  "export_geoJson" : "Export geoJson",
  "export_metadata" : "Export metadata",
  "export_newick" : "Export newick",
  "fetch_error" : "Fetch request failed.",
  "font_size" : "Font size",
  "footer_disclaimer" : "This project is part of the European Joint Programme One Health EJP. This project has received funding from the European Union’s Horizon 2020 Research and Innovation Programme under Grant Agreement No 773830.",
  "for_branches_longer_than" : "Cut off branches longer than",
  "forbidden_net_geojson_alert" : "It seems that you do not have permission to access the GeoJson indicated in the URL. Please try logging in to <a href=\"{0}\" target=\"_blank\">{1}</a> and refresh the page.",
  "forbidden_net_metadata_alert" : "It seems that you do not have permission to access Metadata indicated in the URL. Please try logging in to <a href=\"{0}\" target=\"_blank\">{1}</a> and refresh the page.",
  "forbidden_net_tree_alert" : "It seems that you do not have permission to access the Tree indicated in the URL. Please try logging in to <a href=\"{0}\" target=\"_blank\">{1}</a> and refresh the page.",
  "forbidden_net_zooms_alert" : "It seems that you do not have permission to access the Zooms indicated in the URL. Please try logging in to <a href=\"{0}\" target=\"_blank\">{1}</a> and refresh the page.",
  "from": "From",
  "fullscreen": "Full screen",
  "geojson_file_generic_problem": "It seems there is a problem with the geojson.",
  "gradient": "Warm gradient",
  "gradient_cool": "Cold gradient",
  "gradient_rainbow": "Rainbow",
  "gradient_rainbow2": "Bright rainbow",
  "gradient_rainbow3": "Dark rainbow",
  "grapetree": "GrapeTree",
  "grapetree_tools": "GrapeTree tools",
  "group_order": "Group order",
  "header_index_warning": "WARNING! Header index not defined.",
  "heat_map_mode": "Heatmap mode",
  "help": "Help",
  "helps": {
    "tree_layout": {
      "help": "<ul><li><strong>Centre Tree:</strong> adjusts view settings so that the tree's core is at the centre of the working area.</li><li><strong>Static Redraw:</strong> refreshes the tree and redraws it with the preset layout.</li><li><strong>Original Tree:</strong> reloads the page and restores the tree to the same state and layout it had when it was initially loaded. It will ask for confirmation before leaving the page.<strong>Caution</strong>: this function will cause the loss of all changes you made to the tree.</li></ul>"
    },
    "node_style": {
      "help": "<p>Under this category you can find options to change the node's appearance or displayed information.</p><ul><li><strong>Colour by:</strong>from the dropdown menu of this section it's possible to choose the fill-in colour of the nodes according to metadata.</li><li><strong>Show Labels:</strong> the switch will allow to choose whether to show the node labels or hide them. You can choose which label to show from the dropdown menu just below.</li><li><strong>Font Size:</strong> the font size for the labels can be chosen either by dragging the slider or by specifying a size in the box.</li><li><strong>Highlight Label:</strong> use the text box to provide a search term for the labels to highlight the corresponding nodes. Supports Regular Expressions.</li><li><strong>Individual segments:</strong> use the switch to turn each node into a pie chart showing the breakdown of the members contained in it. The breakdown is based on the category used for the Colour by settings.</li></ul>"
    },
    "node_size": {
      "help": "<ul><li><strong>Node Size (%):</strong> the overall node size can be increased or decreased through this option, either by using the slider or through the box.</li><li><strong>Kurtosis (%):</strong> the area of the nodes is correlated with the members inside them by default. Using this section's slider or box, the node's size can be increased or decreased based on the distribution's kurtosis of the nodes. By increasing this value, you raise the percentage by which the node size grows per member in the node, thus nodes with a larger number of members will have a larger area and will stick out more.</li></ul>"
    },
    "rendering": {
      "help": "<p>This section contains <em>Rendering Layout</em> options, which control how nodes are positioned in the tree. Two modes are available: <em>Static</em> and <em>Dynamic</em>.</p><ul><li><strong>Static:</strong> the tree layout is calculated when the tree is generated and remains static (but interactive); relative branch lenght and scaling (from the original tree data) will always be mantained as long as the <strong>Real Branch Lenght</strong> option is checked.</li><li><strong>Dynamic:</strong> nodes are positioned dynamically in a way similar to a <a href=\"https://gist.github.com/mbostock/4062045\" target=\"_blank\">Force Directed Layout</a> and will try to fan out in order to distance themselves from the neighbours. The tree can be moved around freely by dragging it and the nodes will spread out to mantain the distances among themselves. The <em>Dynamic</em> mode can be used to improve the aesthetics of the tree, but branch lenght scaling will be modified. Branches will NOT be to scale when in <em>Dynamic</em> mode. Toggle on the <strong>Selected Only</strong> option to apply only to selected nodes.</li></ul>"
    },
    "branch_style": {
      "help": "<p>In this section you'll find options to customise the tree's branches.</p><ul><li><strong>Show Labels:</strong> this option will allow you to choose whether to show the branch labels or hide them.</li><li><strong>Font Size:</strong> this option allows you to choose the font size for the labels using the slider or the provided box.</li><li><strong>Scaling (%):</strong> this option allows to increase or decrease the overall branches' lenght, by using the slider or by specifying a value in the box below it.</li><li><strong>Collapse Branches:</strong> use the slider or enter a value in the box to collapse all branches shorter than the specified lenght. Nodes falling in that interval will be merged together. Branch lenght values are scaled to the branch lenghts defined in the original tree data.</li><li><strong>Log Scale:</strong> by checking the box, all lenghts of all branches will be scaled logarithmically.</li></ul>"
    },
    "branch_cutoffs": {
      "help": "<p>The settings in this section will allow to render the branches in different ways depending on their lenght (branch lenght values are scaled to the branch lenghts defined by the data of the original tree). Use the box to enter a value. For branches longer than the specified value it's possible to choose whether to display them, hide them or shorten them:</p><ul><li><strong>Display:</strong> show long branches as normal (default).</li><li><strong>Hide:</strong> makes long branches transparent. Even though the branches are not displayed, it's still possible to interact with them.</li><li><strong>Shorten:</strong> branches longer than the specified cutoff will be cropped back to it. The branches will appear as dashed lines to indicate those that are affected.</li></ul>"
    },
    "map": {
      "help": "<p>Through the options available in this section, you can control the appearance of the map.</p><ul><li><strong>Join by coordinates/by metadata:</strong> The toggle allows you to aggregate points on the map based on the geographical proximity of the provided coordinates or based on the values of the loaded metadata. In the first case, you can define a numerical value for <strong>delta</strong>, which determines the degree of aggregation.</li><li><strong>Minimum/Maximum marker radius:</strong> With these two fields, you can adjust the size of the points on the map by defining a minimum and a maximum radius. The initial size is relative to the number of nodes located at the same geographical coordinates.</li><li><strong>Pie Chart mode/Heatmap mode:</strong> This toggle allows you to change the visualization mode of the points on the map. With the first option (selected by default), the points will be displayed with pie charts based on the categories of the tree nodes, while with the second option, a blur effect is applied to the nodes.</li></ul>"
    },
    "macros": {
      "help": "<p>This section provides a growing collection of action sequences, (macros), which can be searched and categorized by tags.</p><p>The component allows you to search for macros and, by using specific keys, (<strong>title:</strong>, <strong>tag:</strong>, <strong>desc:</strong>), you can narrow your search to focus on specific elements.</p><p>Through the use of the <strong>Ctrl+z</strong> combination, you can undo the application of the macro, while with <strong>Ctrl+y</strong> you can redo it.</p>"
    },
    "feedback": "<p>You can find the complete documentation on our <a href=\"https://github.com/genpat-it/spread/wiki\" target=\"_blank\">wiki</a>. Please visit also <a href=\"https://enterobase.readthedocs.io/en/latest/grapetree/grapetree-about.html\" target=\"_blank\">EnteroBase documentation</a>.</p>"
  },
  "hide": "Hide",
  "hide_labels": "Hide labels",
  "hide_sample_list": "Hide sample list",
  "hide_selected_nodes": "Hide selected nodes",
  "hide_selection_alerts": "Hide selection alerts",
  "highlight_labels": "Highlight labels",
  "histogram_view": "Histogram view",
  "im_fine_thanks": "I'm fine thanks",
  "individual_segments": "Individual segments",
  "input_output": "Input/Output",
  "invert_selection": "Invert selection",
  "join_by_coordinates": "Join by coordinates",
  "join_by_metadata": "Join by metadata",
  "keywords": "Keywords...",
  "kurtosis": "Kurtosis (%)",
  "labels": "Labels",
  "label_asc": "Name ascending",
  "label_desc": "Name descending",
  "label_to_highlight": "Label to highlight...",
  "last_updated_on": "Last updated on",
  "legend": "Legend",
  "legend_tools": "Legend tools",
  "list_view": "List view",
  "load_cluster": "Load cluster",
  "load_cluster_in_new_tab": "Load in new tab",
  "load_failed": "Loading failed",
  "load_grapetree": "Load GrapeTree",
  "load_spread": "Load SPREAD",
  "load_tree": "Load tree",
  "log_scale" : "Log scale",
  "lon_lat_comma_alert": "Some latitude and/or longitude values provided in the metadata contain a comma instead of a dot and have been corrected.",
  "lon_lat_comma_alert_feedback": "This change may cause issues with map display.",
  "m_upload_file_label": "Upload .json, .nwk or .tsv file...",
  "macros" : "Macros",
  "malformed_metadata_file_msg": "It seems the metatada file is malformed.",
  "map": "Map",
  "map_tools": "Map tools",
  "max_marker_radius": "Max marker radius",
  "maximum_group_number": "Maximum number of groups",
  "metadata": "Metadata",
  "metadata_file_generic_problem": "It seems there is a problem with the metadata file.",
  "metadata_geo_problems": "It seems there is a problem on the definition of geographic coordinates (lat, lon) in the metadata file.",
  "metadata_tools": "Metadata tools",
  "min_marker_radius": "Min marker radius",
  "minimum_group_size": "Mininimum group size",
  "missing_net_geo_alert": "It seems there is a problem with the geojson indicated in the url.",
  "missing_net_tree_alert": "It seems there is a problem with the tree file indicated in the url.",
  "missing_net_tsv_alert": "It seems there is a problem with the metadata file indicated in the url.",
  "missing_net_zooms_alert": "It seems there is a problem with the zooms file indicated in the url.",
  "missing_tree_alert": "A file with the tree should be loaded first.",
  "missing_tree_alert_macros": "Oops! It is necessary to upload a file to build the tree before being able to use the macros.",
  "missing_tree_alert_search_engine": "Oops! It is necessary to upload a file to build the tree before being able to use the search function.",
  "move_to_first_position" : "Move to the first position",
  "no_additional_metadata_available" : "No additional metadata is available.",
  "no_category": "No category",
  "no_geo_info_message": "Oops! No geospatial information was found in the uploaded data.",
  "no_item_selected": "No item selected!",
  "no_metadata_info_message": "Oops! No metadata information was found in the uploaded data.",
  "no_options_available": "No options available",
  "no_sample_selected": "No sample selected",
  "node_size": "Node size",
  "node_style": "Node style",
  "not_color_by_defined_category": "No coloring by defined category",
  "not_found_net_geojson_alert" : "I can't find the GeoJson indicated in the URL; please try to verify that the path and/or file name are correct.",
  "not_found_net_metadata_alert" : "I can't find Metadata indicated in the URL; please try to verify that the path and/or file name are correct.",
  "not_found_net_tree_alert" : "I can't find the Tree indicated in the URL; please try to verify that the path and/or file name are correct.",
  "not_found_net_zooms_alert" : "I can't find the Zooms indicated in the URL; please try to verify that the path and/or file name are correct.",
  "numeric": "Numeric",
  "oops": "Oops! Something went wrong.",
  "oops_not_found_http": "Oops! File not found.",
  "oops_forbidden_http": "Oops! Permission denied.",
  "original_tree": "Original tree",
  "pie_chart_mode": "Pie Chart mode",
  "please_note": "Please note",
  "possible_performance_issues_message" : "You might experience performance issues when displaying the expanded tree. I suggest setting the link distance to <strong>{0}</strong>.",
  "publications": "Publications",
  "quick_gradient": "Quick gradient",
  "radius_size": "Radius size (%)",
  "real_branch_length" : "Real branch length",
  "related_nodes_selection" : "Related nodes selection",
  "remove_column": "Remove column",
  "rendering": "Rendering",
  "reset_default": "Torna alle impostazioni di default",
  "reset_to_initial_values": "Reset to initial values",
  "resize_columns" : "Resize columns",
  "run" : "Run",
  "save_as_complete_json" : "Save as complete JSON",
  "save_as_newick" : "Save as Newick",
  "save_feedback_geojson" : "Oops! It seems there are no geographical information defined for the current tree.",
  "save_feedback_json" : "Oops! It seems there are some problems with the current tree.",
  "save_feedback_metadata" : "Oops! It seems there are no metatadata defined for the current tree.",
  "save_feedback_newick" : "Oops! It seems that the information necessary to build a Newick is not available for the current tree.",
  "save_grapetree": "Save GrapeTree",
  "save_spread": "Save SPREAD",
  "save_tree": "Save tree",
  "scaling": "Scaling (%)",
  "search_a_function": "Search for a function",
  "search_a_macro": "Search for a macro",
  "see_available_clusters": "See available clusters",
  "see_available_zooms" : "See available zooms",
  "see_clusters_zooms": "See cluster zooms",
  "select": "Select",
  "select_a_file": "Select a file",
  "select_all": "Select all",
  "select_all_items": "Select all items",
  "select_column": "Select column",
  "select_closest": "Select closest",
  "select_cluster": "Select cluster",
  "select_file_msg": "Please select a file to load.",
  "select_format_to_download" : "Select format to download",
  "select_involved_nodes": "Select involved nodes",
  "select_involved_nodes_empty_feedback": "Samples were not found in metadata.",
  "select_language": "Select language",
  "select_sample": "Select sample",
  "select_threshold": "Select threshold",
  "select_tree_message": "Select a sample to see it in the tree",
  "select_zoom_type": "Select zoom type",
  "selected_only" : "Selected only",
  "selected_samples": "Selected samples",
  "selected_threshold_not_found_in_metadata": "Selected threshold is not in metadata.",
  "set_as_figure_legend": "Set as figure legend",
  "set_radius": "Set radius",
  "set_value": "Set value",
  "settings": "Settings",
  "shorten": "Shorten",
  "show_hypothetical": "Show hypothetical",
  "show_labels": "Show labels",
  "show_metadata": "Show metadata",
  "show_sample_list": "Show sample list",
  "show_selected_subtrees": "Show selected subtrees",
  "show_selection_alerts": "Show selection alerts",
  "show_tooltips": "Show tooltips",
  "show_whole_tree": "Show whole tree",
  "size_asc": "Size ascending",
  "size_desc": "Size descending",
  "spread_tools": "SPREAD tools",
  "static": "Static",
  "static_redraw": "Static redraw",
  "support": "Support",
  "to": "To",
  "total_samples": "Total samples",
  "thresholds_not_found_in_metadata" : "Thresholds not found in metadata.",
  "tree_layout": "Tree layout",
  "tree_tools": "Tree tools",
  "unable_to_get_spread": "I was unable to get SPREAD as object.",
  "unreal_branch_length" : "Unreal branch length",
  "upload": "Upload",
  "use_current_settings": "Use current settings",
  "useful_links" : "Useful links",
  "video": "Video",
  "visual_selection": "Visual selection",
  "zooms_available_for_selected_nodes" : "Zooms available for the selected nodes",
  "zooms_available_for_selected_nodes_info" : "You can disable zoom selection alerts from <strong>Available zooms</strong> context menu.",
  "zooms_available_for_selected_nodes_message" : "One or more selected nodes contain samples for which zooms are available.",
  "zoomed_clusters": "Zoomed clusters",
  "zooms_clusters_generic_problem": "It seems there is a problem with the clusters definition.",
  "zooms_found": "Zooms available",
  "zooms_found_for_clusters": "Zooms available for clusters",
  "zooms_found_for_clusters_info": "You can also see them using the <strong>Clusters zoom</strong> contextual menu at the top right of the component.",
  "zooms_found_for_clusters_message": "The current tree has zooms for one or more clusters.",
  "zooms_found_info": "You can also see them using the <strong>Available zooms</strong> contextual menu at the top right of the component.",
  "zooms_found_message": "The current tree has a zoom for one or more detail type.",
  "zooms_tools": "Zoom tools"
};
/**
 * Français
 * 
 */
gtiz_languages.fr = {
  "_description": "Français",
  "add" : "Ajoutez",
  "add_column" : "Ajoutez une colonne",
  "add_metadata" : "Ajoutez des métadonnées",
  "add_metadata_for_selection" : "Ajoutez des métadonnées pour la sélection",
  "all": "Tous",
  "all_fields_required_message": "Oops! Tous les champs sont obligatoires!",
  "available_zooms": "Zooms disponibles",
  "back_to_full_tree" : "Retournez à l'arborescence complète",
  "branch_cutoffs": "Cl&#244;tures de la branche",
  "branch_style": "Style des branches",
  "cannot_remove_column_message" : "Je ne pux pas supprimer la colonne indiquée; vous perdriez la liaison des métadonnées avec l'arborescence.",
  "cannot_remove_samples_column_message" : "Il n'est pas possible de supprimer les colonnes des échantillons.",
  "category": "Catégorie",
  "category2": "Catégorie 2",
  "centre_tree": "Centrez l'arborescence",
  "change_language": "Changez de langue",
  "change_language_alert" : "<p><i class=\"iconic iconic-warning-triangle\"></i> En changeant la langue l'application sera réinitialisée.</p>",
  "character": "Caractère",
  "clean_selection": "Effacez la sélection",
  "closest": "Closest",
  "cluster": "Cluster",
  "clusters": "Clusters",
  "clusters_by_category_and_mst_not_found" : "Aucun cluster n'a été trouvé à partir des catégories et des seuils fournis: {0}.",
  "clusters_zooms" : "Zooms des clusters",
  "clusters_zooms_tools": "Outils zoom des clusters",
  "collapse_branches": "Repliez les branches",
  "collapse_selected_nodes": "Repliez les n&#156;uds sélectionnés",
  "color_by": "Colorez par",
  "color_by_defined_category": "Colorez par catégorie définie",
  "color_scheme": "Schéma de couleurs",
  "cookies_notice": "Cette application n'utilise pas de cookies.",
  "crn_genome_sequencing": "CRN Séquençage Génomique",
  "custom": "Personnalisé",
  "data_category": "Catégorie de données",
  "define_a_default_value": "Définissez une valeur par défaut",
  "define_a_value_for_selected": "Définissez une valeur pour les sélectionnés",
  "define_a_value_for_unselected": "Définissez une valeur pour les non sélectionnés",
  "define_column": "Définissez la colonne",
  "define_for_selected": "Définissez pour les sélectionnés",
  "define_for_unselected": "Définissez pour les non sélectionnés",
  "define_metadata": "Définissez la métadonnée",
  "delete": "Supprimez",
  "delete_metadata" : "Supprimez les métadonnées",
  "deselect_all": "Désélectionnez tous",
  "display": "Affichez",
  "do_not_use_current_settings": "Ne pas utiliser les paramètres actuels",
  "download": "Download",
  "download_image": "Download l'image",
  "download_table": "Download la table",
  "drop_info": "Vous pouvez également glisser ou download un fichier .nwk suivi d'un fichier .tsv contenant les métadonnées à associer à l'arborescence. Optionnellement, vous pouvez glisser un fichier .geojson contenant des informations géospatiales. Vous pouvez trouver un guide complet sur notre <a href=\"https://github.com/genpat-it/spread/wiki\" target=\"_blank\">wiki</a>.",
  "drop_message": "Veuillez glisser ici un fichier .json valide ou chargez-le depuis votre ordinateur pour commencer avec SPREAD.",
  "dropped_files_alert": "Vous pouvez glisser un seul fichier à la fois: un fichier <strong>.json</strong> complet ou alternativement un fichier <strong>.nwk</strong> puis un fichier <strong>.tsv</strong> avec les métadonnées et enfin, éventuellement, un fichier <strong>.geojson</strong> avec les informations spatiales.",
  "dynamic" : "Dynamique",
  "edit": "Modifiez",
  "edit_metadata": "Modifiez les métadonnées",
  "edit_metadata_for_selection": "Modifiez les métadonnées pou la sélection",
  "expand_all": "Développez tout",
  "expand_selected_nodes": "Développez les n&#156;uds sélectionnés",
  "export_geoJson" : "Exportez geoJson",
  "export_metadata" : "Exportez les métadonnées",
  "export_newick" : "Exportez newick",
  "fetch_error" : "La demande d'upload du fichier a échoué.",
  "font_size" : "Taille de police",
  "footer_disclaimer" : "Ce projèt fait partie de l'European Joint Programme One Health EJP. Le projet a reçu un financement du Programme de Recherche et Innovation Horizon 2020 de l'Union Européenne dans le cadre du Grant Agreement No 773830.",
  "for_branches_longer_than" : "Coupez les branches plus longues que",
  "forbidden_net_geojson_alert" : "Il semble que vous n'ayez pas les autorisations pour accéder au GeoJson indiqué dans l'URL. Veuillez essayer de faire le login sur <a href=\"{0}\" target=\"_blank\">{1}</a> et rafra&#238;chir la page.",
  "forbidden_net_metadata_alert" : "Il semble que vous n'ayez pas les autorisations pour accéder aux Métadonnées indiquées dans l'URL. Veuillez essayer de faire le login sur <a href=\"{0}\" target=\"_blank\">{1}</a> et rafra&#238;chir la page.",
  "forbidden_net_tree_alert" : "Il semble que vous n'ayez pas les autorisations pour accéder à l'Arborescence indiquée dans l'URL. Veuillez essayer de faire le login sur <a href=\"{0}\" target=\"_blank\">{1}</a> et rafra&#238;chir la page.",
  "forbidden_net_zooms_alert" : "Il semble que vous n'ayez pas les autorisations pour accéder au Zooms indiqués dans le URL. Veuillez essayer de faire le login sur <a href=\"{0}\" target=\"_blank\">{1}</a> et rafra&#238;chir la page.",
  "from": "Du",
  "fullscreen": "Plein écran",
  "geojson_file_generic_problem": "Il semble y avoir un problème avec le geojson.",
  "gradient": "Gradient chaud",
  "gradient_cool": "Gradient froid",
  "gradient_rainbow": "Arc-en-ciel",
  "gradient_rainbow2": "Arc-en-ciel clair",
  "gradient_rainbow3": "Arc-en-ciel sombre",
  "grapetree": "GrapeTree",
  "grapetree_tools": "Outils GrapeTree",
  "group_order": "Ordre du groupe",
  "header_index_warning": "ATTENTION! Index d'en-t&#234;te non défini.",
  "heat_map_mode": "Mode heatmap",
  "help": "Aide",
  "helps": {
    "tree_layout": {
      "help": "<ul><li><strong>Centrez l'Arborescence:</strong> ajuste les paramètres d'affichage de façon à ce que le centre de l'arborescence soit au centre de la zone de travail.</li><li><strong>Redessin Statique:</strong> met à jour l'arborescence et la redessine avec le layout actuel.</li><li><strong>Arborescence Originale:</strong> recharge la page et rétablit l'arbre dans l'état et le layout qu'il avait lors de son chargement initial. Il vous demandera une confirmation avant de quitter la page.<strong>Attention</strong>: cette fonction entra&#238;nera la perte de toutes les modifications apportées à l'arborescence.</li></ul>"
    },
    "node_style": {
      "help": "<p>Dans cette catégorie il est possible de trouver des options pour modifier l'apparence des n&#156;uds ou les informations affichées.</p><ul><li><strong>Coloriez par:</strong>depuis le menu déroulant de cette section, il est possible de sélectionner la couleur de remplissage des n&#156;uds en fonction des métadonnées.</li><li><strong>Affichez les étiquettes:</strong> l'option permet de choisir d'afficher ou non les étiquettes des n&#156;uds. Il est également possible de choisir le type d'étiquette à afficher depuis le menu déroulant ci-dessous.</li><li><strong>Taille de police:</strong> la taille de police pour les étiquettes peut &#234;tre choisie soit en faisant glisser le curseur approprié, soit en spécifiant une valeur dans le champ en dessous.</li><li><strong>Mettez en surbrillance l'étiquette:</strong> utilisez le champ de texte pour fournir un terme de recherche pour mettre en surbrillance les n&#156;uds correspondants aux étiquettes. Les Expressions Régulières sont prises en charge.</li><li><strong>Segments individuels:</strong> utilisez cette option pour transformer chaque n&#156;ud en un graphique circulaire affichiant la répartition des éléments qu'il contient. Cette répartition est basée sur la catégorie utilisée pour les paramètres de Coloriez par</li></ul>"
    },
    "node_size": {
      "help": "<ul><li><strong>Taille des N&#156;uds (%):</strong> la taille totale des n&#156;uds peut &#234;tre augmentée ou diminuée en faisant glisser le curseur approprié ou en spécifiant les dimensions dans le champ prévu.</li><li><strong>Kurtose (%):</strong> la surface des n&#156;uds est corrélée par défaut au nombre d'éléments qu'ils contiennent. En utilisant le curseur ou le champ prévu dans cette section, la taille des n&#156;uds peut &#234;tre augmentée ou diminuée sur la base de la kurtose de la distribution des n&#156;uds. &#192; mesure que la valeur de la kurtose augmente, le pourcentage par lequel la taille du n&#156;ud grandit, pour chaque élément en son sein, augmente également; par conséquent, les n&#156;uds contenant un plus grand nombre d'éléments auront une plus grande surface et ressortiront davantage.</li></ul>"
    },
    "rendering": {
      "help": "<p>La section <em>Layout de Rendu</em> contient des options permettant de contr&#244;ler le positionnement des n&#156;uds dans l'arborescence. Deux modes sont disponibles: <em>Statique</em> et <em>Dynamique</em>.</p><ul><li><strong>Statique:</strong> le layout de l'arborescence est calculé lors de la génération du graphe et reste statique (mais interactif); la longueur relative des branches et leur échelle (dérivées des données originales de l'arborescence) seront toujours conservées tant que l'option <strong>Longueur de la branche réelle</strong> reste sélectionnée.</li><li><strong>Dynamique:</strong> les n&#156;uds sont positionnés dynamiquement de manière similaire à un <a href=\"https://gist.github.com/mbostock/4062045\" target=\"_blank\">Layout par Forces Dirigées</a> mais ils ont tendance à se disperser pour s'éloigner les uns des autres.Dans ce mode, l'arborescence peut &#234;tre déplacée librement en la faisant glisser et les n&#156;uds se disperseront pour mantenir des distances entre eux. Le mode <em>Dynamique</em> peut &#234;tre utilisé pour améliorer l'esthétique de l'arborescence mais la longueur des branches à l'échelle sera modifiée. Les branches NE seront PAS à l'échelle en mode <em>Dynamique</em>. Activez l'option <strong>Sélectionnés uniquement</strong> pour appliquer le choix uniquement aux n&#156;uds sélectionnés.</li></ul>"
    },
    "branch_style": {
      "help": "<p>Dans cette section vous trouverez les options pour personnaliser les branches de l'arborescence.</p><ul><li><strong>Affichez les étiquettes:</strong> cette option vous permet de choisir d'afficher ou de masquer les étiquettes des branches.</li><li><strong>Taille de police:</strong> cette option vous permettra de choisir la taille de police pour les étiquettes, en utilisant le curseur ou le champ prévu.</li><li><strong>Ajustement à l'échelle (%):</strong> cette option vous permettra d'augmenter ou diminuer la longueur totale des branches, en utilisant le curseur ou en spécifiant une valeur dans le champ au-dessous.</li><li><strong>Repliez les Branches:</strong> utilisez le curseur ou saisissez une valeur dans le champ prévu pour replier toutes les branches plus courtes que la longueur spécifiée. Les n&#156;uds tombant dans cet intervalle seront fusionnés. Les valeurs de longueur des branches sont mises à l'échelle selon les longueurs définies dans les données de l'arborescence originale.</li><li><strong>&#201;chelle logarithmique:</strong> en sélectionnant cette option, les longueurs de toutes les branches seront ajustées selon une échelle logarithmique.</li></ul>"
    },
    "branch_cutoffs": {
      "help": "<p>Les paramètres de cette section permettent de représenter les branches de différentes manières en fonction de leur longueur (les valeurs de longueur des branches sont mises à l'échelle par rapport aux longueurs des branches définies dans les données de l'arborescence originale). Veuillez utiliser le champ prévu pour saisir une valeur. Pour les branches plus longues que la valeur spécifiée, il est possible de choisir de les afficher, de les masquer ou de les raccourcir:</p><ul><li><strong>Affichez:</strong> cette option affiche les branches plus longues que la valeur spécifiée comme normales (par défaut).</li><li><strong>Masquez:</strong> cette choix rend transparentes les branches plus longues que la valeur spécifiée. Bien que les branches ne soient pas affichées, il est possible d'interagir avec elles.</li><li><strong>Raccourcissez:</strong> les branches plus longues que la valeur-seuil spécifiée seront réduites à celle-ci. Les branches réduites appara&#238;tront sous forme de lignes en pointillés pour indiquer celles qui ont été affectées par la modification.</li></ul>"
    },
    "map": {
      "help": "<p>Les options de cette section vous permettront de contr&#244;ler l'apparence de la carte.</p><ul><li><strong>Agrégez par coordonnées/par métadonnées:</strong> Le commutateur vous permet d'agréger les points sur la carte en fonction de la proximité géographique des coordonnées fournies ou des valeurs des métadonnées importées. Dans le premier cas, vous pouvez définir une valeur numérique pour le <strong>delta</strong>, qui détermine le degré d'agrégation.</li><li><strong>Minimum/Rayon Minimal/Maximal du marqueur:</strong> ces deux champs vour permettent d'ajuster la taille des points sur la carte en définissant un rayon minimal et un rayon maximal. La taille initiale est relative au nombre de n&#156;uds situés sur les m&#234;mes coordonnées géographiques.</li><li><strong>Mode Diagramme en Secteurs/Mode Carte Thermique:</strong> Le commutateur vous permet de modifier les modes d'affichage des points sur la carte. Avec la première option (sélectionnée par défaut) les points seront affichés sous forme de diagramme en secteurs selon les catégories des n&#156;uds de l'arborescence, tandis qu'avec la seconde, en effet de flou est appliqué aux n&#156;uds.</li></ul>"
    },
    "macros": {
      "help": "<p>Cette section propose une collection croissante de séquences d'actions, (macros), qui peuvent &#234;tre recherchées et catégorisées par tags.</p><p>Les composants permettent de rechercher les macros et, en utilisant des clés spécifiques, (<strong>title:</strong>, <strong>tag:</strong>, <strong>desc:</strong>), il est possible de restreindre la recherche pour se concentrer sur des éléments spécifiques.</p><p>En utilisant la combinaison <strong>Ctrl+z</strong> vous pouvez annuler l'application de la macro, tandis qu'avec <strong>Ctrl+y</strong> vous pouvez la rétablir.</p>"
    },
    "feedback": "<p>Vous pouvez trouver la documentation complète sur nostre <a href=\"https://github.com/genpat-it/spread/wiki\" target=\"_blank\">wiki</a>. Veuillez consulter également <a href=\"https://enterobase.readthedocs.io/en/latest/grapetree/grapetree-about.html\" target=\"_blank\">EnteroBase documentation</a>.</p>"
  },
  "hide": "Masquez",
  "hide_labels": "Masquez les étiquettes",
  "hide_sample_list": "Masquez la liste des échantillons",
  "hide_selected_nodes": "Masquez les n&#156;uds sélectionnés",
  "hide_selection_alerts": "Masquez les alertes de sélection",
  "highlight_labels": "Mettez en surbrillance les étiquettes",
  "histogram_view": "Vue en histogramme",
  "im_fine_thanks": "&#199;a va comme ça, merci",
  "individual_segments": "Segments individuels",
  "input_output": "Entrée/Sortie",
  "invert_selection": "Inversez la sélection",
  "join_by_coordinates": "Agrégez par coordonnées",
  "join_by_metadata": "Agrégez par métadonnées",
  "keywords": "Mots-clés...",
  "kurtosis": "Kurtose (%)",
  "labels": "&#201;tiquettes",
  "label_asc": "Nom ascendant",
  "label_desc": "Nom descendant",
  "label_to_highlight": "&#201;tiquette à surligner...",
  "last_updated_on": "Dernière mise à jour le",
  "legend": "Légende",
  "legend_tools": "Outils de la légende",
  "list_view": "Vue à liste",
  "load_cluster": "Chargez le cluster",
  "load_cluster_in_new_tab": "Ouvrez dans un nouvel onglet",
  "load_failed": "&#201;chec du chargement",
  "load_grapetree": "Chargez GrapeTree",
  "load_spread": "Chargez SPREAD",
  "load_tree": "Chargez l'arborescence",
  "log_scale" : "&#201;chelle logarithmique",
  "lon_lat_comma_alert": "Certaines valeurs de latitude et/ou longitude fournies dans les métadonnées contiennent une virgule au lieu d'un point et ont été corrigées:",
  "lon_lat_comma_alert_feedback": "Cette modification pourrait entra&#238;ner des problèmes d'affichage de la carte.",
  "m_upload_file_label": "S'il vous plait, upload un fichier .json, .nwk ou .tsv...",
  "macros" : "Macros",
  "malformed_metadata_file_msg": "Il semble que le fichier des métadonnées ne soit pas bien formé.",
  "map": "Carte",
  "map_tools": "Outils pour la carte",
  "max_marker_radius": "Rayon maximal du marqueur",
  "maximum_group_number": "Nombre maximal de groupes",
  "metadata": "Métadonnées",
  "metadata_file_generic_problem": "Il semble y avoir un problème avec le fichier des métadonnées.",
  "metadata_geo_problems": "Il semble y avoir un problème avec la définition des coordonnées géographiques (lat, lon) dans le fichier des métadonnées.",
  "metadata_tools": "Outils pour les métadonnées",
  "min_marker_radius": "Rayon minimal du marqueur",
  "minimum_group_size": "Taille minimale du groupe",
  "missing_net_geo_alert": "Il semble y avoir un problème avec le geojson indiqué dans l'url.",
  "missing_net_tree_alert": "Il semble y avoir un problème avec le fichier de l'arborescence indiqué dans l'url.",
  "missing_net_tsv_alert": "Il semble y avoir un problème avec le fichier des métadonnées indiqué dans l'url.",
  "missing_net_zooms_alert": "Il semble y avoir un problème avec le fichier des zooms indiqué dans l'url.",
  "missing_tree_alert": "Veuillez d'abord charger un fichier avec l'arborescence.",
  "missing_tree_alert_macros": "Oops! S'il vous plait, upload un fichier pour la construction de l'arborescence avant de pouvoir utiliser les macros.",
  "missing_tree_alert_search_engine": "Oops! S'il vous plait, upload un fichier pour la construction de l'arborescence avant de pouvoir utiliser la fonction de recherche.",
  "move_to_first_position" : "Déplacez en première position",
  "no_additional_metadata_available" : "Aucune métadonnée supplémentaire n'est disponible.",
  "no_category": "Aucune catégorie",
  "no_geo_info_message": "Oops! Aucune information géospatiale n'a été trouvée parmi les données chargées.",
  "no_item_selected": "Aucun élément sélectionné!",
  "no_metadata_info_message": "Oops! Aucune information sur les métadonnées n'a été trouvée parmi les données chargées.",
  "no_options_available": "Aucune option n'est disponible",
  "no_sample_selected": "Aucun échantillon sélectionné",
  "node_size": "Taille des n&#156;uds",
  "node_style": "Style des n&#156;uds",
  "not_color_by_defined_category": "Ne colorez pas par catégorie définie",
  "not_found_net_geojson_alert" : "Je ne trouve pas le GeoJson indiqué dans l'url; s'il vous plait, veuillez vérifier que le chemin et/ou le nom du fichier sont corrects.",
  "not_found_net_metadata_alert" : "Je ne trouve pas les Métadonnées indiquées dans l'url; veuillez vérifier que le chemin et/ou le nom du fichier sont corrects.",
  "not_found_net_tree_alert" : "Je ne trouve pas l'Arborescence indiquée dans l'url; veuillez vérifier que le chemin et/ou le nom du fichier sont corrects.",
  "not_found_net_zooms_alert" : "Je ne trouve pas les Zooms indiqués dans l'url; veuillez vérifier que le chemin et/ou le nom du fichier sont corrects.",
  "numeric": "Numérique",
  "oops": "Oops! Quelque chose a mal tourné!.",
  "oops_not_found_http": "Oops! Fichier non trouvé.",
  "oops_forbidden_http": "Oops! Autorisation refusée.",
  "original_tree": "Arborescence originale",
  "pie_chart_mode": "Mode graphique en secteurs",
  "please_note": "&#192; noter",
  "possible_performance_issues_message" : "Vous pourriez rencontrer des problèmes de performance en affichant l'arborescence étendue. Je suggère de régler la distance des liens sur <strong>{0}</strong>.",
  "publications": "Publications",
  "quick_gradient": "Gradient rapide",
  "radius_size": "Taille du rayon (%)",
  "real_branch_length" : "Longueur de la branche réelle",
  "related_nodes_selection" : "Sélection des n&#156;uds associés",
  "remove_column": "Supprimez la colonne",
  "rendering": "Rendu",
  "reset_default": "Revenez aux paramètres par défaut",
  "reset_to_initial_values": "Réinitialisez aux valeurs initiales",
  "resize_columns" : "Redimensionnez les colonnes",
  "run" : "Lancez",
  "save_as_complete_json" : "Enregistrez comme JSON complet",
  "save_as_newick" : "Enregistrez comme Newick",
  "save_feedback_geojson" : "Oops! Il semble qu'il n'y ait aucune infomation géographique définie pour l'arborescence actuelle.",
  "save_feedback_json" : "Oops! Il semble y avoir des problèmes avec l'arborescence actuelle.",
  "save_feedback_metadata" : "Oops! Il semble qu'il n'y ait aucune métadonnée définie pour l'arborescence actuelle.",
  "save_feedback_newick" : "Oops! Il semble que les informations nécessaires à la construction d'un Newick ne soient pas disponibles pour l'arborescence actuelle.",
  "save_grapetree": "Enregistrez le GrapeTree",
  "save_spread": "Enregistrez le SPREAD",
  "save_tree": "Enregistrez l'arborescence",
  "scaling": "Ajustement à l'échelle (%)",
  "search_a_function": "Recherchez une fonction",
  "search_a_macro": "Recherchez une macro",
  "see_available_clusters": "Voyez les clusters disponibles",
  "see_available_zooms" : "Voyez les zooms disponibles",
  "see_clusters_zooms": "Voyez les zooms des clusters",
  "select": "Sélectionnez",
  "select_a_file": "Sélectionnez un fichier",
  "select_all": "Tout sélectionner",
  "select_all_items": "Sélectionnez tous les éléments",
  "select_column": "Sélectionnez une colonne",
  "select_closest": "Sélectionnez closest",
  "select_cluster": "Sélectionnez un cluster",
  "select_file_msg": "S'il vous plait, sélectionnez un fichier à charger.",
  "select_format_to_download" : "Sélectionnez le format pour le download",
  "select_involved_nodes": "Sélectionnez les n&#156;uds interessés",
  "select_involved_nodes_empty_feedback": "&#201;chantillons non trouvés dans les métadonnées.",
  "select_language": "Sélectionnez la langue",
  "select_sample": "Select sample",
  "select_threshold": "Sélectionnez le seuil",
  "select_tree_message": "Sélectionnez un échantillon pour le voir dans l'arborescence",
  "select_zoom_type": "Sélectionnez le type de zoom",
  "selected_only" : "Seulement les sélectionnés",
  "selected_samples": "&#201;chantillons sélectionnés",
  "selected_threshold_not_found_in_metadata": "Le seuil sélectionné n'est pas dans les métadonnées.",
  "set_as_figure_legend": "Définissez comme légende de la figure",
  "set_radius": "Définissez le rayon",
  "set_value": "Définissez la valeur",
  "settings": "Paramètres",
  "shorten": "Raccourcissez",
  "show_hypothetical": "Affichez les éléments hypothétiques",
  "show_labels": "Affichez les étiquettes",
  "show_metadata": "Affichez les métadonnées",
  "show_sample_list": "Affichez la liste des échantillons",
  "show_selected_subtrees": "Affichez les sous-arborescences sélectionnées",
  "show_selection_alerts": "Affichez les alertes de sélection",
  "show_tooltips": "Affichez les info-bulles",
  "show_whole_tree": "Affichez l'arborescence intière",
  "size_asc": "Taille ascendente",
  "size_desc": "Taille décroissante",
  "spread_tools": "Outils du SPREAD",
  "static": "Statique",
  "static_redraw": "Rendu statique",
  "support": "Support",
  "to": "Jusqu'au",
  "total_samples": "Nombre total d'échantillons",
  "thresholds_not_found_in_metadata" : "Seuils non trouvés dans les métadonnées.",
  "tree_layout": "Layout en arborescence",
  "tree_tools": "Outils de l'arborescence",
  "unable_to_get_spread": "Je n'ai pas réussi à obtenir SPREAD comme objet.",
  "unreal_branch_length" : "Longueur de la branche non réelle",
  "upload": "Upload",
  "use_current_settings": "Utilisez les paramètres actuels",
  "useful_links" : "Liens utiles",
  "video": "Vidéo",
  "visual_selection": "Sélection visuelle",
  "zooms_available_for_selected_nodes" : "Zooms disponibles pour les n&#156;uds sélectionnés",
  "zooms_available_for_selected_nodes_info" : "Vous pouvez désactiver les alertes de sélection des zooms depuis le menu contextuel <strong>Zooms disponibles</strong>.",
  "zooms_available_for_selected_nodes_message" : "Un ou plusieurs n&#156;uds sélectionnés contiennent des échantillons pour lesquels des agrandissements sont disponibles.",
  "zoomed_clusters": "Clusters agrandis",
  "zooms_clusters_generic_problem": "Il semble y avoir un problème avec la définition des clusters.",
  "zooms_found": "Des zooms sont disponibles",
  "zooms_found_for_clusters": "Des zooms sont disponibles pour les clusters",
  "zooms_found_for_clusters_info": "Vous pouvez également les voir en utilisant le menu contextuel <strong>Zoom des clusters</strong> en haut à droite du composant.",
  "zooms_found_for_clusters_message": "L'arborescence actuelle a des zooms pour un ou plusieurs clusters.",
  "zooms_found_info": "Vous pouvez également les voir en utilisant le menu contextuel <strong>Zooms disponibles</strong> en haut à droite du composant.",
  "zooms_found_message": "L'arborescence actuelle a des zooms disponibles pour un ou plusieurs types de détail.",
  "zooms_tools": "Outils zoom"
};
/**
 * Italiano
 * 
 */
gtiz_languages.it = {
  "_description": "Italiano",
  "add": "Aggiungi",
  "add_column": "Aggiungi colonna",
  "add_metadata": "Aggiungi metadati",
  "add_metadata_for_selection": "Aggiungi metadati per selezione",
  "all": "Tutti",
  "all_fields_required_message": "Ops! Tutti i campi sono obbligatori!",
  "available_zooms": "Zoom disponibili",
  "back_to_full_tree": "Torna all'albero completo",
  "branch_cutoffs": "Tagli collegamento",
  "branch_style": "Stile collegamenti",
  "cannot_remove_column_message": "Non posso rimuovere la colonna indicata; perderesti il collegamento dei metadati con l'albero.",
  "cannot_remove_samples_column_message": "Non è possibile rimuovere colonne dei campioni.",
  "category": "Categoria",
  "category2": "Categoria 2",
  "centre_tree": "Centra albero",
  "change_language": "Cambia lingua",
  "change_language_alert": "<p><i class=\"iconic iconic-warning-triangle\"></i> Cambiando lingua l'applicazione subirà un reset.</p>",
  "character": "Carattere",
  "clean_selection": "Pulisci selezione",
  "closest": "Closest",
  "cluster": "Cluster",
  "clusters": "Clusters",
  "clusters_by_category_and_mst_not_found": "Non sono stati trovati clusters a partire da categorie e soglie fornite: {0}.",
  "clusters_zooms": "Zoom dei cluster",
  "clusters_zooms_tools": "Strumenti zoom dei cluster",
  "collapse_branches": "Comprimi collegamenti",
  "collapse_selected_nodes": "Comprimi nodi selezionati",
  "color_by": "Colora per",
  "color_by_defined_category": "Colora per categoria definita",
  "color_scheme": "Schema colore",
  "cookies_notice": "Questa applicazione non utilizza cookies.",
  "crn_genome_sequencing": "CRN Sequenziamento Genomico",
  "custom": "Personalizzato",
  "data_category": "Categoria dati",
  "define_a_default_value": "Definisci un valore di default",
  "define_a_value_for_selected": "Definisci un valore per i selezionati",
  "define_a_value_for_unselected": "Definisci un valore per i non selezionati",
  "define_column": "Definisci colonna",
  "define_for_selected": "Definisci per selezionati",
  "define_for_unselected": "Definisci per non selezionati",
  "define_metadata": "Definisci metadato",
  "delete": "Elimina",
  "delete_metadata": "Elimina metadati",
  "deselect_all": "Deseleziona tutti",
  "display": "Mostra",
  "do_not_use_current_settings": "Non usare impostazioni correnti",
  "download": "Download",
  "download_image": "Scarica immagine",
  "download_table": "Download tabella",
  "drop_info": "Puoi anche trascinare o caricare un file .nwk seguito da un file .tsv per i metadati da associare all'albero. Opzionalmente puoi trascinare o caricare un file .geojson contenente informazioni geospaziali. Puoi trovare una guida completa sul nostro <a href=\"https://github.com/genpat-it/spread/wiki\" target=\"_blank\">wiki</a>.",
  "drop_message": "Trascina in quest'area un file .json valido oppure caricalo dal tuo computer per iniziare con SPREAD.",
  "dropped_files_alert": "Puoi trascinare un solo file per volta: un file <strong>.json</strong> completo o in alternativa un file <strong>.nwk</strong> seguito da un file <strong>.tsv</strong> con i metadati, infine eventualmente un file <strong>.geojson</strong> con le informazioni geospaziali.",
  "dynamic": "Dinamico",
  "edit": "Modifica",
  "edit_metadata": "Modifica metadati",
  "edit_metadata_for_selection": "Modifica metadati per selezione",
  "expand_all": "Espandi tutti",
  "expand_selected_nodes": "Espandi nodi selezionati",
  "export_geoJson": "Esporta geoJson",
  "export_metadata": "Esporta metadati",
  "export_newick": "Esporta newick",
  "fetch_error": "La richiesta di caricamento del file non è riuscita.",
  "font_size": "Dimensione carattere",
  "footer_disclaimer": "Questo progetto fa parte dell'European Joint Programme One Health EJP. Il progetto ha ricevuto finanziamenti dal Programma di Ricerca e Innovazione Horizon 2020 dell'Unione Europea nell'ambito del Grant Agreement No 773830.",
  "for_branches_longer_than": "Taglia collegamenti più lunghi di",
  "forbidden_net_geojson_alert": "Sembra che tu non abbia i permessi per accedere al GeoJson indicato nella URL. Prova a fare login su <a href=\"{0}\" target=\"_blank\">{1}</a> ed aggiorna la pagina.",
  "forbidden_net_metadata_alert": "Sembra che tu non abbia i permessi per accedere ai Metadati indicati nella URL. Prova a fare la login su <a href=\"{0}\" target=\"_blank\">{1}</a> ed aggiorna la pagina.",
  "forbidden_net_tree_alert": "Sembra che tu non abbia i permessi per accedere all'Albero indicato nella URL. Prova a fare la login su <a href=\"{0}\" target=\"_blank\">{1}</a> ed aggiorna la pagina.",
  "forbidden_net_zooms_alert": "Sembra che tu non abbia i permessi per accedere agli Zoom indicati nella URL. Prova a fare la login su <a href=\"{0}\" target=\"_blank\">{1}</a> ed aggiorna la pagina.",
  "from": "Dal",
  "fullscreen": "Schermo intero",
  "geojson_file_generic_problem": "Sembra esserci un problema con il geojson.",
  "gradient": "Gradiente caldo",
  "gradient_cool": "Gradiente freddo",
  "gradient_rainbow": "Arcobaleno",
  "gradient_rainbow2": "Arcobaleno chiaro",
  "gradient_rainbow3": "Arcobaleno scuro",
  "grapetree": "GrapeTree",
  "grapetree_tools": "Strumenti GrapeTree",
  "group_order": "Ordine gruppo",
  "header_index_warning": "ATTENZIONE! Indice in intestazione non definito.",
  "heat_map_mode": "Modalità heatmap",
  "help": "Aiuto",
  "helps": {
    "tree_layout": {
      "help": "<ul><li><strong>Centra Albero:</strong> regola le impostazioni di visualizzazione in modo tale che il centro dell'albero sia al centro dell'area di lavoro.</li><li><strong>Ridisegno Statico:</strong> aggiorna l'albero e lo ridisegna con il layout attuale.</li><li><strong>Albero Originale:</strong> ricarica lapagina e ripristina lo stato ed il layout che l'albero aveva quando è stato inizialmente caricato. Chiederà conferma prima di abbandonare la pagina.<strong>Attenzione</strong>: questa funzione causerà la perdita di tutte le modifiche apportate all'albero.</li></ul>"
    },
    "node_style": {
      "help": "<p>In questa categoria è possibile trovare opzioni per modificare l'aspetto dei nodi o le informazioni visualizzate.</p><ul><li><strong>Colora per:</strong>dal menù a cascata di questa sezione, è possibile selezionare il colore di riempimento dei nodi, in base ai metadati.</li><li><strong>Mostra etichette:</strong> l'opzione permette di scegliere se visualizzare o meno le etichette dei nodi. &#200; anche possibile scegliere che tipo di etichetta mostrare dal menù a cascata qui sotto.</li><li><strong>Dimensione carattere:</strong> la dimensione del carattere per le etichette può essere scelta o trascinando l'apposito cursore oppure specificando una misura nel campo sottostante.</li><li><strong>Evidenzia etichetta:</strong> usa il campo di testo per fornire un termine di ricerca per evidenziare i nodi corrispondenti alle etichette. Sono supportate le Espressioni Regolari.</li><li><strong>Segmenti individuali:</strong> usa l'opzione per trasformare ciascun nodo in un grafico a torta che mostri la scomposizione degli elementi in esso contenuti. Tale scomposizione è basata sulla categoria utilizzata per le impostazioni di Colora per</li></ul>"
    },
    "node_size": {
      "help": "<ul><li><strong>Dimensione dei nodi (%):</strong> la dimensione complessiva dei nodi può essere aumentata o diminuita trascinando l'apposito cursore o specificando le dimensioni nel campo previsto.</li><li><strong>Curtosi (%):</strong> l'area dei nodi è correlata di default con il numero di elementi che ne fanno parte. Usando il cursore o il campo previsto di questa sezione, le dimensioni dei nodi possono essere diminuite o aumentate sulla base della curtosi della distribuzione dei nodi. All'aumentare del valore della curtosi, aumenta la percentuale attraverso la quale cresce la dimensione del nodo per ogni elemento al suo interno; di conseguenza, i nodi con un numero maggiore di elementi avranno un'area più grande e risalteranno di più.</li></ul>"
    },
    "rendering": {
      "help": "<p>La sezione <em>Layout di Rendering</em> contiene alcune opzioni che permettono di controllare il posizionamento dei nodi nell'albero. Sono disponibili due modalità: <em>Statico</em> e <em>Dinamico</em>.</p><ul><li><strong>Statico:</strong> il layout dell'albero viene calcolato alla generazione del grafico e rimane statico (ma interattivo); la lunghezza relativa dei rami e la loro scala (derivate dai dati originali dell'albero) saranno sempre mantenute fintanto che l'opzione <strong>Lunghezza del ramo reale</strong> rimane selezionata.</li><li><strong>Dinamico:</strong> i nodi sono posizionati dinamicamente in maniera simile ad un <a href=\"https://gist.github.com/mbostock/4062045\" target=\"_blank\">Layout a Forze Dirette</a> ma tendono a sparpagliarsi per distanziarsi tra loro. In questa modalità, l'albero può essere spostato liberamente, trascinandolo, e i nodi si sparpaglieranno per mantenere le distanze tra loro. La modalità <em>Dinamica</em> può essere usata per migliorare l'estetica dell'albero ma la lunghezza dei rami in scala verrà modificata. I rami NON saranno in scala se in modalità <em>Dynamic</em>. Attiva l'opzione <strong>Solo selezionati</strong> per applicare la scelta solo ai nodi selezionati.</li></ul>"
    },
    "branch_style": {
      "help": "<p>In questa sezione troverai le opzioni per personalizzare i rami dell'albero.</p><ul><li><strong>Mostra etichette:</strong> l'opzione permette di scegliere se mostrare o nascondere le etichette dei rami.</li><li><strong>Dimensione carattere:</strong> questa opzione ti permette di scegliere le dimensioni del carattere delle etichette, utilizzando il cursore o l'apposito campo.</li><li><strong>Adattamento in scala (%):</strong> questa opzione ti permette di aumentare o diminuire la lunghezza complessiva dei rami, utilizzando il cursore o specificando un valore nel campo sottostante.</li><li><strong>Comprimi i Rami:</strong> utilizza il cursore o inserisci un valore nel campo previsto per comprimere tutti i rami più corti della lunghezza specificata. I nodi che rientrano nell'intervallo verranno fusi. I valori delle lunghezze dei rami sono in scala sulla base delle lunghezze dei rami definite nei dati dell'albero originale.</li><li><strong>Scala logaritmica:</strong> selezionando questa opzione, le lunghezze di tutti i rami verranno adattate in scala logaritmica.</li></ul>"
    },
    "branch_cutoffs": {
      "help": "<p>Le impostazioni in questa sezione permettono di rappresentare i rami in modi diversi a seconda della loro lunghezza (i valori di lunghezza dei rami sono in scala rispetto alle lunghezze dei rami definite dai dati dell'albero originale). Utilizza l'apposito campo per inserire un valore. Per i rami più lunghi del valore specificato, è possibile scegliere se mostrarli, nasconderli o accorciarli:</p><ul><li><strong>Mostra:</strong> mostra i rami più lunghi come normali (predefinito).</li><li><strong>Nascondi:</strong> rende trasparenti i rami più lunghi. Sebbene i rami non siano mostrati, è possibile interagire con essi.</li><li><strong>Accorcia:</strong> i rami più lunghi del valore-soglia specificato verranno ridotti ad esso. I rami ridotti appariranno come linee tratteggiate ad indicare quelli che sono stati interessati dalla modifica.</li></ul>"
    },
    "map": {
      "help": "<p>Attraverso le opzioni presenti in questa sezione, puoi controllare l'aspetto della mappa.</p><ul><li><strong>Aggrega per coordinate/per metadati:</strong> l'interruttore permette di aggregare i punti sulla mappa in base alla vicinanza geografica delle coordinate fornite o ai valori dei metadati caricati. Nel primo caso, è possibile definire un valore numerico per <strong>delta</strong> che determina il grado di aggregazione.</li><li><strong>Raggio Minimo/Massimo del marcatore:</strong> questi due campi permettono di intervenire sulla dimensione dei punti sulla mappa, definendo un raggio minimo ed un raggio massimo. La dimensione iniziale è relativa al numero di nodi presenti sulle stesse coordinate geografiche.</li><li><strong>Modalità grafico a torta/Modalità mappa di calore:</strong> l'interruttore permette di cambiare la modalità di visualizzazione dei punti sulla mappa. Con la prima opzione (selezionata di default) i punti saranno visualizzati con dei grafici a torta in base alle categorie dei nodi dell'albero mentre, con la seconda, ai nodi viene applicato un effetto sfocato.</li></ul>"
    },
    "macros": {
      "help": "<p>Questa sezione offre una crescente raccolta di sequenze di azioni, (macro), che possono essere ricercate e categorizzate per tag.</p><p>I componenti consentono di cercare le macro e, utilizzando chiavi specifiche, (<strong>title:</strong>, <strong>tag:</strong>, <strong>desc:</strong>), è possibile restringere la ricerca per concentrarsi su elementi specifici.</p><p>Attraverso l'utilizzo della combinazione <strong>Ctrl+z</strong> puoi annullare l'applicazione della macro mentre con <strong>Ctrl+y</strong> puoi ripristinarla.</p>"
    },
    "feedback": "<p>Puoi trovare la documentazione completa sul nostro <a href=\"https://github.com/genpat-it/spread/wiki\" target=\"_blank\">wiki</a>. Puoi anche consultare la documentazione ufficiale di <a href=\"https://enterobase.readthedocs.io/en/latest/grapetree/grapetree-about.html\" target=\"_blank\">EnteroBase</a>.</p>"
  },
  "hide": "Nascondi",
  "hide_labels": "Nascondi etichette",
  "hide_sample_list": "Nascondi lista campioni",
  "hide_selected_nodes": "Nascondi nodi selezionati",
  "hide_selection_alerts": "Nascondi avvisi di selezione",
  "highlight_labels": "Evidenzia etichette",
  "histogram_view": "Visualizzazione a istogramma",
  "im_fine_thanks": "Va bene così, grazie",
  "individual_segments": "Segmenti individuali",
  "input_output": "Input/Output",
  "invert_selection": "Inverti selezione",
  "join_by_coordinates": "Aggrega per coordinate",
  "join_by_metadata": "Aggrega per metadati",
  "keywords": "Parole chiave...",
  "kurtosis": "Curtosi (%)",
  "labels": "Etichette",
  "label_asc": "Nome ascendente",
  "label_desc": "Nome discendente",
  "label_to_highlight": "Etichetta da evidenziare...",
  "last_updated_on": "Ultimo aggiornamento il",
  "legend": "Legenda",
  "legend_tools": "Strumenti legenda",
  "list_view": "Visualizzazione a lista",
  "load_cluster": "Carica cluster",
  "load_cluster_in_new_tab": "Apri in nuova scheda",
  "load_failed": "Caricamento fallito",
  "load_grapetree": "Carica GrapeTree",
  "load_spread": "Carica SPREAD",
  "load_tree": "Carica albero",
  "log_scale": "Scala logaritmica",
  "lon_lat_comma_alert": "Alcuni valori di latitudine e/o longitudine forniti nei metadati contengono una virgola anziché un punto e sono stati corretti.",
  "lon_lat_comma_alert_feedback": "Questa modifica potrebbe causare problemi nella visualizzazione della mappa.",
  "m_upload_file_label": "Carica un file .json, .nwk o .tsv..",
  "macros": "Macro",
  "malformed_metadata_file_msg": "Sembra che il file dei metadati non sia formattato correttamente.",
  "map": "Mappa",
  "map_tools": "Strumenti mappa",
  "max_marker_radius": "Raggio massimo del marcatore",
  "maximum_group_number": "Numero massimo di gruppi",
  "metadata": "Metadati",
  "metadata_file_generic_problem": "Sembra esserci un problema con il file dei metadati.",
  "metadata_geo_problems": "Sembra esserci un problema con la definizione delle coordinate geografiche (lat, lon) nel file dei metadati.",
  "metadata_tools": "Strumenti metadati",
  "min_marker_radius": "Raggio minimo del marcatore",
  "minimum_group_size": "Grandezza minima gruppo",
  "missing_net_geo_alert": "Sembra esserci un problema con il geojson indicato nella url.",
  "missing_net_tree_alert": "Sembra esserci un problema con il file dell'albero indicato nella url.",
  "missing_net_tsv_alert": "Sembra esserci un problema con il file dei metadati indicato nella url.",
  "missing_net_zooms_alert": "Sembra esserci un problema con il file degli zoom indicato nella url.",
  "missing_tree_alert": "Dovresti prima caricare un file con l'albero.",
  "missing_tree_alert_macros": "Ops! Dovresti caricare un file per la costruzione dell'albero prima di poter utilizzare le macro.",
  "missing_tree_alert_search_engine": "Ops! Dovresti caricare un file per la costruzione dell'albero prima di poter utilizzare la funzione di ricerca.",
  "move_to_first_position": "Sposta in prima posizione",
  "no_additional_metadata_available": "Nessun ulteriore metadato è disponibile.",
  "no_category": "Nessuna categoria",
  "no_geo_info_message": "Ops! Non ho trovato alcuna informazione geospaziale tra i dati caricati.",
  "no_item_selected": "Nessun elemento selezionato!",
  "no_metadata_info_message": "Ops! Non ho trovato alcuna informazione sui metadati tra i dati caricati.",
  "no_options_available": "Nessuna opzione disponibile",
  "no_sample_selected": "Nessun campione selezionato",
  "node_size": "Dimensione nodi",
  "node_style": "Stile nodi",
  "not_color_by_defined_category": "Non colorare per la categoria definita",
  "not_found_net_geojson_alert": "Non riesco a trovare il GeoJson indicato nella URL; prova a verificare che percorso e/o nome del file siano corretti.",
  "not_found_net_metadata_alert": "Non riesco a trovare i Metadati indicati nella URL; prova a verificare che percorso e/o nome del file siano corretti.",
  "not_found_net_tree_alert": "Non riesco a trovare l'Albero indicato nella URL; prova a verificare che percorso e/o nome del file siano corretti.",
  "not_found_net_zooms_alert": "Non riesco a trovare gli Zoom indicati nella URL; prova a verificare che percorso e/o nome del file siano corretti.",
  "numeric": "Numerico",
  "oops": "Ops! Qualcosa è andato storto.",
  "oops_not_found_http": "Ops! File non trovato.",
  "oops_forbidden_http": "Ops! Permesso negato.",
  "original_tree": "Albero iniziale",
  "pie_chart_mode": "Modalità grafico a torta",
  "please_note": "Nota bene",
  "possible_performance_issues_message": "Potresti avere problemi di performance visualizzando l'albero esteso. Suggerisco di impostare la distanza dei collegamenti su <strong>{0}</strong>.",
  "publications": "Pubblicazioni",
  "quick_gradient": "Gradiente veloce",
  "radius_size": "Dimensione raggio (%)",
  "real_branch_length": "Lunghezza del ramo reale",
  "related_nodes_selection": "Selezione nodi correlati",
  "remove_column": "Rimuovi colonna",
  "rendering": "Rendering",
  "reset_default": "Reset to default",
  "reset_to_initial_values": "Ripristina ai valori iniziali",
  "resize_columns": "Ridimensiona colonne",
  "run": "Lancia",
  "save_as_complete_json": "Salva come JSON completo",
  "save_as_newick": "Salva come Newick",
  "save_feedback_geojson": "Ops! Sembra che non ci siano informazioni geografiche definite per l'albero corrente.",
  "save_feedback_json": "Ops! Sembra che ci siano dei problemi con l'albero corrente.",
  "save_feedback_metadata": "Ops! Sembra che non ci siano metadati definiti per l'albero corrente.",
  "save_feedback_newick": "Ops! Sembra che le informazioni necessarie alla costruzione di un newick non siano disponibili per l'albero corrente.",
  "save_grapetree": "Salva GrapeTree",
  "save_spread": "Salva SPREAD",
  "save_tree": "Salva albero",
  "scaling": "Adattamento in scala (%)",
  "search_a_function": "Cerca una funzione",
  "search_a_macro": "Cerca una macro",
  "see_available_clusters": "Mostra cluster disponibili",
  "see_available_zooms": "Mostra zoom disponibili",
  "see_clusters_zooms": "Mostra gli zoom dei cluster",
  "select": "Seleziona",
  "select_a_file": "Seleziona un file",
  "select_all": "Seleziona tutto",
  "select_all_items": "Seleziona tutti gli elementi",
  "select_column": "Seleziona colonna",
  "select_closest": "Seleziona closest",
  "select_cluster": "Seleziona cluster",
  "select_file_msg": "Per favore seleziona un file da caricare.",
  "select_format_to_download": "Seleziona il formato da scaricare",
  "select_involved_nodes": "Seleziona nodi coinvolti",
  "select_involved_nodes_empty_feedback": "Campioni non trovati nei metadati.",
  "select_language": "Seleziona lingua",
  "select_sample": "Seleziona campione",
  "select_threshold": "Seleziona soglia",
  "select_tree_message": "Seleziona un campione per vederlo nell'albero",
  "select_zoom_type": "Seleziona tipo di zoom",
  "selected_only": "Solo selezionati",
  "selected_samples": "Campioni selezionati",
  "selected_threshold_not_found_in_metadata": "La soglia selezionata non è presente nei metadati.",
  "set_as_figure_legend": "Imposta come legenda della figura",
  "set_radius": "Imposta raggio",
  "set_value": "Imposta valore",
  "settings": "Impostazioni",
  "shorten": "Riduci",
  "show_hypothetical": "Mostra elementi ipotetici",
  "show_labels": "Mostra etichette",
  "show_metadata": "Mostra metadati",
  "show_sample_list": "Mostra lista campioni",
  "show_selected_subtrees": "Mostra i sottoalberi selezionati",
  "show_selection_alerts": "Mostra avvisi di selezione",
  "show_tooltips": "Mostra suggerimenti",
  "show_whole_tree": "Mostra albero intero",
  "size_asc": "Grandezza ascendente",
  "size_desc": "Grandezza discendente",
  "spread_tools": "Strumenti SPREAD",
  "static": "Statico",
  "static_redraw": "Ridisegno statico",
  "support": "Supporto",
  "to": "Al",
  "total_samples": "Numero totale di campioni",
  "thresholds_not_found_in_metadata": "Soglie non trovate nei metadati.",
  "tree_layout": "Layout ad albero",
  "tree_tools": "Strumenti albero",
  "unable_to_get_spread": "Non sono stato in grado di ottenere SPREAD come oggetto.",
  "unreal_branch_length": "Lunghezza del ramo non reale",
  "upload": "Upload",
  "use_current_settings": "Usa impostazioni correnti",
  "useful_links": "Link utili",
  "video": "Video",
  "visual_selection": "Selezione visiva",
  "zooms_available_for_selected_nodes": "Zoom disponibili per i nodi selezionati",
  "zooms_available_for_selected_nodes_info": "Puoi disabilitare gli avvisi di selezione degli zoom dal menu contestuale <strong>Zoom disponibili</strong>.",
  "zooms_available_for_selected_nodes_message": "Uno o più nodi selezionati contengono campioni per cui sono disponibili ingrandimenti.",
  "zoomed_clusters": "Cluster ingranditi",
  "zooms_clusters_generic_problem": "Sembra ci sia un problema con la definizione dei clusters.",
  "zooms_found": "Sono disponibili degli zoom",
  "zooms_found_for_clusters": "Sono disponibili degli zoom per i cluster",
  "zooms_found_for_clusters_info": "Puoi vederli anche utilizzando il menu contestuale <strong>Zoom dei cluster</strong> in alto a destra del componente.",
  "zooms_found_for_clusters_message": "L'albero corrente ha degli zoom per uno o più cluster.",
  "zooms_found_info": "Puoi vederli anche utilizzando il menu contestuale <strong>Zoom disponibili</strong> in alto a destra del componente.",
  "zooms_found_message": "L'albero corrente ha degli zoom disponibili per una o più tipologia di dettaglio.",
  "zooms_tools": "Strumenti zoom"
};
