name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACTION_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker build . --file Dockerfile --tag ghcr.io/genpat-it/spread:latest
          docker push ghcr.io/genpat-it/spread:latest
