name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'  # Prevent running if GitHub Actions made the push
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Replace placeholder with current date
        run: |
          DATE=`date +'%Y-%m-%d %H:%M:%S'`
          sed -i "s/__LAST_UPDATE__/$DATE/" index.html
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add index.html
          git commit -m "Update index.html with current date"
          git push

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        run: |
          docker build . --file Dockerfile --tag ghcr.io/genpat-it/spread:latest
          docker push ghcr.io/genpat-it/spread:latest
